"""Foundational tools for generalized semi-Clifford analysis."""

from .analytic_fixtures import (
    AnalyticGSCFixture,
    analytic_gsc_fixtures,
    one_qubit_equal_axis_rotation_fixture,
    one_qubit_phase_fixture,
    two_qubit_controlled_phase_fixture,
)
from .benchmarking import (
    GSC_BENCHMARK_SCHEMA,
    GSCBenchmarkMeasurements,
    GSCBenchmarkRecord,
    GSCBenchmarkRun,
    GSCBenchmarkWorkload,
    build_gsc_benchmark_record,
    run_gsc_sampling_benchmark,
)
from .conjugation_sampling import (
    ConjugationBackend,
    ConjugationContainmentResult,
    ConjugationSample,
    ConjugationWord,
    ContainmentStatus,
    SamplingLimitExceeded,
    evaluate_conjugation_word,
    sample_conjugation_word,
    sample_subgroup_escape_word,
    test_clifford_conjugation_containment,
)
from .conjugation_tester import (
    ConjugationDistanceEvidence,
    ConjugationProbeResult,
    DenseConjugationBackend,
    GSCSandwichResult,
    HierarchyDistanceEvidence,
    SandwichStatus,
    check_gsc_sandwich,
    probe_gsc_conjugation_condition,
    probe_hierarchy_distance,
    semi_clifford_distance_lower_bound,
)
from .gsc_qiskit import (
    CircuitGSCWitness,
    GSCDiscoveryVerificationResult,
    GSCSamplingResult,
    empirical_lagrangian_leakage,
    find_gsc_sampling_witness,
    lagrangian_leakage_upper_bound,
    output_pauli_probabilities,
    run_gsc_discovery_then_verification,
    run_gsc_sampling_test,
    run_gsc_witness_test,
)
from .lagrangian import (
    Lagrangian,
    PauliLabel,
    enumerate_lagrangians,
    lagrangian_containing,
    lagrangian_count,
    lagrangian_from_basis,
)
from .semi_clifford_qiskit import (
    PauliConjugationObservation,
    SemiCliffordSamplingResult,
    SemiCliffordWitness,
    bell_bitstring_to_pauli,
    bell_counts_to_observation,
    build_pauli_conjugation_test_circuit,
    build_semi_clifford_test_circuits,
    find_lagrangian_witness,
    maximum_isotropic_dimension,
    run_semi_clifford_sampling_test,
    run_semi_clifford_witness_test,
    symplectic_pairing,
)
from .statistics import binomial_proportion_upper_bound, zero_event_shots_required
from .symplectic import identity, is_symplectic, matmul, standard_form, transpose
from .tester import GSCStatus, GSCWitness, NaiveGSCResult, check_gsc_naive, verify_gsc_witness

__all__ = [
    "AnalyticGSCFixture",
    "ConjugationBackend",
    "ConjugationContainmentResult",
    "ConjugationDistanceEvidence",
    "ConjugationProbeResult",
    "ConjugationSample",
    "ConjugationWord",
    "ContainmentStatus",
    "DenseConjugationBackend",
    "GSCSandwichResult",
    "HierarchyDistanceEvidence",
    "SandwichStatus",
    "SamplingLimitExceeded",
    "CircuitGSCWitness",
    "GSC_BENCHMARK_SCHEMA",
    "GSCBenchmarkMeasurements",
    "GSCBenchmarkRecord",
    "GSCBenchmarkRun",
    "GSCBenchmarkWorkload",
    "GSCDiscoveryVerificationResult",
    "GSCStatus",
    "GSCSamplingResult",
    "GSCWitness",
    "Lagrangian",
    "NaiveGSCResult",
    "PauliConjugationObservation",
    "PauliLabel",
    "SemiCliffordSamplingResult",
    "SemiCliffordWitness",
    "bell_bitstring_to_pauli",
    "bell_counts_to_observation",
    "binomial_proportion_upper_bound",
    "analytic_gsc_fixtures",
    "build_pauli_conjugation_test_circuit",
    "build_semi_clifford_test_circuits",
    "build_gsc_benchmark_record",
    "check_gsc_naive",
    "check_gsc_sandwich",
    "empirical_lagrangian_leakage",
    "enumerate_lagrangians",
    "evaluate_conjugation_word",
    "find_gsc_sampling_witness",
    "find_lagrangian_witness",
    "identity",
    "is_symplectic",
    "lagrangian_count",
    "lagrangian_containing",
    "lagrangian_from_basis",
    "lagrangian_leakage_upper_bound",
    "matmul",
    "maximum_isotropic_dimension",
    "output_pauli_probabilities",
    "one_qubit_equal_axis_rotation_fixture",
    "one_qubit_phase_fixture",
    "probe_gsc_conjugation_condition",
    "probe_hierarchy_distance",
    "run_gsc_discovery_then_verification",
    "run_gsc_sampling_test",
    "run_gsc_sampling_benchmark",
    "run_gsc_witness_test",
    "run_semi_clifford_sampling_test",
    "run_semi_clifford_witness_test",
    "sample_conjugation_word",
    "sample_subgroup_escape_word",
    "semi_clifford_distance_lower_bound",
    "standard_form",
    "symplectic_pairing",
    "transpose",
    "test_clifford_conjugation_containment",
    "two_qubit_controlled_phase_fixture",
    "verify_gsc_witness",
    "zero_event_shots_required",
]
__version__ = "0.4.0"
