"""Small analytically justified fixtures for dense GSC checks.

The matrices returned here are floating-point representations, but each
fixture records a short algebraic reason for its expected classification.
They are intended for examples, regression tests, and cross-checking future
backends rather than as a substitute for an exact proof engine.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

from .lagrangian import lagrangian_from_basis
from .tester import GSCStatus, GSCWitness

ComplexMatrix = NDArray[np.complex128]

_I = np.eye(2, dtype=np.complex128)
_X = np.array([[0, 1], [1, 0]], dtype=np.complex128)
_Y = np.array([[0, -1j], [1j, 0]], dtype=np.complex128)
_Z = np.array([[1, 0], [0, -1]], dtype=np.complex128)


@dataclass(frozen=True)
class AnalyticGSCFixture:
    """A numerical matrix paired with an independently stated exact claim."""

    name: str
    unitary: ComplexMatrix
    expected_status: GSCStatus
    expected_semi_clifford: bool
    witness: GSCWitness | None
    rejected_witnesses: tuple[GSCWitness, ...]
    justification: str
    basis_permutation: tuple[int, ...] | None = None

    def __post_init__(self) -> None:
        matrix = np.array(self.unitary, dtype=np.complex128, copy=True)
        matrix.setflags(write=False)
        object.__setattr__(self, "unitary", matrix)
        if self.basis_permutation is not None:
            permutation = tuple(self.basis_permutation)
            dimension = matrix.shape[0]
            if sorted(permutation) != list(range(dimension)):
                raise ValueError(
                    "basis_permutation must permute every computational-basis index"
                )
            expected = np.zeros_like(matrix)
            expected[permutation, np.arange(dimension)] = 1
            if not np.array_equal(matrix, expected):
                raise ValueError("unitary does not implement basis_permutation")
            object.__setattr__(self, "basis_permutation", permutation)


def _validated_angle(angle: float) -> float:
    value = float(angle)
    if not math.isfinite(value):
        raise ValueError("angle must be finite")
    return value


def one_qubit_phase_fixture(angle: float = math.pi / 4) -> AnalyticGSCFixture:
    """Return ``diag(1, exp(i angle))`` with its fixed-Z witness.

    Every member of this family commutes with ``Z``. It is therefore
    semi-Clifford, and hence GSC, independently of the angle.
    """

    value = _validated_angle(angle)
    z_masa = lagrangian_from_basis(((0, 1),), 1)
    x_masa = lagrangian_from_basis(((1, 0),), 1)
    return AnalyticGSCFixture(
        name="one-qubit phase",
        unitary=np.diag([1, np.exp(1j * value)]),
        expected_status=GSCStatus.GSC,
        expected_semi_clifford=True,
        witness=GSCWitness(z_masa, z_masa, 0.0),
        rejected_witnesses=(GSCWitness(x_masa, z_masa, 0.0),),
        justification="The diagonal unitary fixes Z under conjugation.",
    )


def two_qubit_controlled_phase_fixture(
    angle: float = math.pi / 4,
) -> AnalyticGSCFixture:
    """Return ``diag(1, 1, 1, exp(i angle))`` with its fixed-Z MASA.

    The full two-qubit diagonal Pauli MASA generated by ``Z_0`` and ``Z_1``
    commutes with every member of this family, providing a semi-Clifford and
    GSC witness for every finite angle.
    """

    value = _validated_angle(angle)
    z_masa = lagrangian_from_basis(((0, 0, 1, 0), (0, 0, 0, 1)), 2)
    x_masa = lagrangian_from_basis(((1, 0, 0, 0), (0, 1, 0, 0)), 2)
    return AnalyticGSCFixture(
        name="two-qubit controlled phase",
        unitary=np.diag([1, 1, 1, np.exp(1j * value)]),
        expected_status=GSCStatus.GSC,
        expected_semi_clifford=True,
        witness=GSCWitness(z_masa, z_masa, 0.0),
        rejected_witnesses=(GSCWitness(z_masa, x_masa, 0.0),),
        justification="Every diagonal operator commutes with the Z-generated Pauli MASA.",
    )


def one_qubit_equal_axis_rotation_fixture() -> AnalyticGSCFixture:
    """Return a provably non-GSC one-qubit rotation.

    This is a Bloch-sphere rotation by ``pi / 3`` about ``(1, 1, 1) / sqrt(3)``.
    Rodrigues' formula gives three nonzero Pauli coefficients in the image of
    each of ``X``, ``Y``, and ``Z`` (absolute values ``1/3, 2/3, 2/3``).
    Consequently no one-qubit Pauli MASA is mapped to a Pauli MASA. For one
    qubit, the semi-Clifford and GSC conditions coincide.
    """

    angle = math.pi / 3
    axis = (_X + _Y + _Z) / math.sqrt(3)
    unitary = math.cos(angle / 2) * _I - 1j * math.sin(angle / 2) * axis
    return AnalyticGSCFixture(
        name="one-qubit equal-axis rotation",
        unitary=unitary,
        expected_status=GSCStatus.NOT_GSC,
        expected_semi_clifford=False,
        witness=None,
        rejected_witnesses=(),
        justification=(
            "Each Pauli generator has three nonzero Pauli coefficients after "
            "conjugation, so no one-dimensional Pauli MASA is preserved or exchanged."
        ),
    )


def three_qubit_cyclic_permutation_fixture() -> AnalyticGSCFixture:
    """Return a minimal-qubit GSC gate that is not semi-Clifford.

    The permutation fixes basis indices 0 through 4 and cycles ``5 -> 6 -> 7
    -> 5``.  Every basis permutation normalizes the diagonal matrix algebra,
    so the Z-generated Pauli MASA supplies a GSC witness.

    An exact bit-table calculation shows that ``Z_0`` is the only nonidentity
    Pauli whose conjugate is a Pauli.  No three-dimensional Pauli Lagrangian
    can lie in that one-dimensional set, so the gate is not semi-Clifford.
    Three qubits are minimal: every permutation of one or two bits is affine,
    hence Clifford, and Clifford multiplication preserves semi-Cliffordness.
    """

    permutation = (0, 1, 2, 3, 4, 6, 7, 5)
    unitary = np.zeros((8, 8), dtype=np.complex128)
    unitary[permutation, np.arange(8)] = 1
    z_masa = lagrangian_from_basis(
        (
            (0, 0, 0, 1, 0, 0),
            (0, 0, 0, 0, 1, 0),
            (0, 0, 0, 0, 0, 1),
        ),
        3,
    )
    x_masa = lagrangian_from_basis(
        (
            (1, 0, 0, 0, 0, 0),
            (0, 1, 0, 0, 0, 0),
            (0, 0, 1, 0, 0, 0),
        ),
        3,
    )
    return AnalyticGSCFixture(
        name="three-qubit cyclic permutation",
        unitary=unitary,
        expected_status=GSCStatus.GSC,
        expected_semi_clifford=False,
        witness=GSCWitness(z_masa, z_masa, 0.0),
        rejected_witnesses=(GSCWitness(x_masa, z_masa, 0.0),),
        justification=(
            "The basis permutation normalizes the diagonal algebra, while exact "
            "conjugation of all 63 nonidentity Paulis leaves only Z_0 Pauli-valued; "
            "that one-dimensional set contains no three-qubit Lagrangian."
        ),
        basis_permutation=permutation,
    )


def analytic_gsc_fixtures() -> tuple[AnalyticGSCFixture, ...]:
    """Return the package's deterministic one- through three-qubit catalog."""

    return (
        one_qubit_phase_fixture(),
        two_qubit_controlled_phase_fixture(),
        one_qubit_equal_axis_rotation_fixture(),
        three_qubit_cyclic_permutation_fixture(),
    )
